# This is a basic workflow to help you get started with Actions

name: Deploy to github actions bruh.

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Copy files to root directory.
      - name: make gh-pages format
        run: cd src && mv * ../ 

      # 
      - name: commit it to gh-pages branch
        run: |
          git config --global user.email "avinash2000vk@gmail.com"
          git config --global user.name "avinash"
          git add .
          git commit -m "deploying from master"
          git push origin gh-pages
          
          
